/* Maths goblins - https://github.com/jonathankeogh/maths-goblins
   Shows one face in the logo slot and steps to the next one on each page load.

   The faces are data URIs and this file is parsed immediately after the <img>,
   thus the first paint already shows the correct face: no second request, no
   swap, no movement. Generated by src/build_goblins.py - do not edit by hand.
*/
(function () {
    var HEAD = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"320\" height=\"185\" viewBox=\"0 0 320 185\"><g fill=\"#1a1a1a\" font-family=\"STIX Two Text, STIXGeneral, Cambria Math, Georgia, serif\"><text x=\"";
    var TAIL = "></g></svg>";
    var faces = [
        [
                "02_original_prod_face",
                "91\" y=\"103\" font-size=\"34\" text-anchor=\"middle\" font-style=\"italic\" transform=\"scale(-1,1) translate(-182,0)\">&#946;</text><text x=\"123\" y=\"108\" font-size=\"34\" text-anchor=\"middle\" font-style=\"italic\">&#945;</text><text x=\"160\" y=\"115\" font-size=\"38\" text-anchor=\"middle\">&#8719;</text><path d=\"M137 76 Q160 62 183 76\" fill=\"none\" stroke=\"#1a1a1a\" stroke-width=\"2\" stroke-linecap=\"round\"/><text x=\"197\" y=\"108\" font-size=\"34\" text-anchor=\"middle\" font-style=\"italic\">&#945;</text><text x=\"229\" y=\"103\" font-size=\"34\" text-anchor=\"middle\" font-style=\"italic\">&#946;</text><text x=\"160\" y=\"141\" font-size=\"25\" text-anchor=\"middle\" font-style=\"italic\">&#963;</text><text x=\"105\" y=\"125\" font-size=\"38\" text-anchor=\"middle\" font-style=\"italic\" transform=\"rotate(-35 105 125)\">,</text><circle cx=\"99\" cy=\"111\" r=\"1.9\" fill=\"#1a1a1a\"/><text x=\"213\" y=\"125\" font-size=\"38\" text-anchor=\"middle\" font-style=\"italic\" transform=\"rotate(35 213 125) scale(-1,1) translate(-426,0)\">,</text><circle cx=\"220\" cy=\"111\" r=\"1.9\" fill=\"#1a1a1a\"/"
        ],
        [
                "03_scholar",
                "160\" y=\"34\" font-size=\"36\" text-anchor=\"middle\">&#8721;</text><text x=\"160\" y=\"88\" font-size=\"58\" text-anchor=\"middle\">&#8734;</text><text x=\"78\" y=\"86\" font-size=\"44\" text-anchor=\"middle\">(</text><text x=\"242\" y=\"86\" font-size=\"44\" text-anchor=\"middle\">)</text><text x=\"160\" y=\"120\" font-size=\"26\" text-anchor=\"middle\" font-style=\"italic\">&#953;</text><text x=\"160\" y=\"144\" font-size=\"36\" text-anchor=\"middle\">&#8995;</text"
        ],
        [
                "04_cat",
                "112\" y=\"38\" font-size=\"38\" text-anchor=\"middle\">&#923;</text><text x=\"208\" y=\"38\" font-size=\"38\" text-anchor=\"middle\">&#923;</text><text x=\"135\" y=\"82\" font-size=\"28\" text-anchor=\"middle\">&#8226;</text><text x=\"185\" y=\"82\" font-size=\"28\" text-anchor=\"middle\">&#8226;</text><text x=\"160\" y=\"102\" font-size=\"20\" text-anchor=\"middle\">&#8744;</text><text x=\"160\" y=\"128\" font-size=\"30\" text-anchor=\"middle\" font-style=\"italic\">&#969;</text><text x=\"72\" y=\"94\" font-size=\"30\" text-anchor=\"middle\">&#8920;</text><text x=\"248\" y=\"94\" font-size=\"30\" text-anchor=\"middle\">&#8921;</text"
        ],
        [
                "05_surprised",
                "160\" y=\"38\" font-size=\"40\" text-anchor=\"middle\">&#936;</text><text x=\"84\" y=\"92\" font-size=\"40\" text-anchor=\"middle\" font-style=\"italic\">&#949;</text><text x=\"236\" y=\"92\" font-size=\"40\" text-anchor=\"middle\">&#1014;</text><text x=\"130\" y=\"90\" font-size=\"34\" text-anchor=\"middle\">&#8857;</text><text x=\"190\" y=\"90\" font-size=\"34\" text-anchor=\"middle\">&#8857;</text><text x=\"160\" y=\"136\" font-size=\"26\" text-anchor=\"middle\">&#8728;</text"
        ],
        [
                "06_wink",
                "122\" y=\"50\" font-size=\"24\" text-anchor=\"middle\">&#8764;</text><text x=\"190\" y=\"50\" font-size=\"24\" text-anchor=\"middle\">&#8764;</text><text x=\"122\" y=\"88\" font-size=\"38\" text-anchor=\"middle\">&#8853;</text><text x=\"196\" y=\"88\" font-size=\"38\" text-anchor=\"middle\">&#8855;</text><text x=\"80\" y=\"92\" font-size=\"36\" text-anchor=\"middle\" font-style=\"italic\" transform=\"scale(-1,1) translate(-160,0)\">&#950;</text><text x=\"240\" y=\"92\" font-size=\"36\" text-anchor=\"middle\" font-style=\"italic\">&#950;</text><text x=\"160\" y=\"132\" font-size=\"28\" text-anchor=\"middle\">&#8801;</text"
        ],
        [
                "07_walrus",
                "160\" y=\"30\" font-size=\"28\" text-anchor=\"middle\">&#8781;</text><text x=\"84\" y=\"88\" font-size=\"38\" text-anchor=\"middle\" transform=\"scale(-1,1) translate(-168,0)\">&#8472;</text><text x=\"236\" y=\"88\" font-size=\"38\" text-anchor=\"middle\">&#8472;</text><text x=\"135\" y=\"82\" font-size=\"26\" text-anchor=\"middle\">&#8226;</text><text x=\"185\" y=\"82\" font-size=\"26\" text-anchor=\"middle\">&#8226;</text><text x=\"160\" y=\"114\" font-size=\"44\" text-anchor=\"middle\">&#8776;</text><text x=\"140\" y=\"154\" font-size=\"30\" text-anchor=\"middle\">&#8747;</text><text x=\"180\" y=\"154\" font-size=\"30\" text-anchor=\"middle\">&#8747;</text"
        ],
        [
                "08_sad",
                "160\" y=\"34\" font-size=\"34\" text-anchor=\"middle\" font-style=\"italic\">&#950;</text><text x=\"128\" y=\"86\" font-size=\"32\" text-anchor=\"middle\">&#8854;</text><text x=\"192\" y=\"86\" font-size=\"32\" text-anchor=\"middle\">&#8854;</text><text x=\"130\" y=\"112\" font-size=\"22\" text-anchor=\"middle\">&#8242;</text><text x=\"162\" y=\"112\" font-size=\"24\" text-anchor=\"middle\" font-style=\"italic\">&#948;</text><text x=\"160\" y=\"148\" font-size=\"34\" text-anchor=\"middle\">&#8994;</text"
        ],
        [
                "09_robot",
                "160\" y=\"28\" font-size=\"26\" text-anchor=\"middle\">&#8868;</text><text x=\"128\" y=\"80\" font-size=\"32\" text-anchor=\"middle\">&#8865;</text><text x=\"192\" y=\"80\" font-size=\"32\" text-anchor=\"middle\">&#8865;</text><text x=\"78\" y=\"82\" font-size=\"34\" text-anchor=\"middle\">&#8866;</text><text x=\"244\" y=\"82\" font-size=\"34\" text-anchor=\"middle\">&#8867;</text><text x=\"160\" y=\"130\" font-size=\"34\" text-anchor=\"middle\">&#8852;</text"
        ],
        [
                "10_asleep",
                "125\" y=\"82\" font-size=\"26\" text-anchor=\"middle\">&#8764;</text><text x=\"190\" y=\"82\" font-size=\"26\" text-anchor=\"middle\">&#8764;</text><text x=\"82\" y=\"86\" font-size=\"32\" text-anchor=\"middle\" font-style=\"italic\" transform=\"scale(-1,1) translate(-164,0)\">&#963;</text><text x=\"238\" y=\"86\" font-size=\"32\" text-anchor=\"middle\" font-style=\"italic\">&#963;</text><text x=\"160\" y=\"124\" font-size=\"22\" text-anchor=\"middle\">&#8728;</text><text x=\"220\" y=\"38\" font-size=\"20\" text-anchor=\"middle\" font-style=\"italic\">&#950;</text><text x=\"242\" y=\"28\" font-size=\"26\" text-anchor=\"middle\" font-style=\"italic\">&#950;</text><text x=\"268\" y=\"18\" font-size=\"32\" text-anchor=\"middle\" font-style=\"italic\">&#950;</text"
        ],
        [
                "11_in_love",
                "118\" y=\"30\" font-size=\"28\" text-anchor=\"middle\">&#167;</text><text x=\"160\" y=\"26\" font-size=\"32\" text-anchor=\"middle\">&#167;</text><text x=\"198\" y=\"30\" font-size=\"28\" text-anchor=\"middle\">&#167;</text><text x=\"120\" y=\"60\" font-size=\"18\" text-anchor=\"middle\">&#8243;</text><text x=\"192\" y=\"60\" font-size=\"18\" text-anchor=\"middle\">&#8243;</text><text x=\"122\" y=\"86\" font-size=\"28\" text-anchor=\"middle\">&#9825;</text><text x=\"192\" y=\"86\" font-size=\"28\" text-anchor=\"middle\">&#9825;</text><text x=\"80\" y=\"88\" font-size=\"34\" text-anchor=\"middle\" font-style=\"italic\" transform=\"scale(-1,1) translate(-160,0)\">&#962;</text><text x=\"240\" y=\"88\" font-size=\"34\" text-anchor=\"middle\" font-style=\"italic\">&#962;</text><text x=\"82\" y=\"114\" font-size=\"16\" text-anchor=\"middle\">&#8728;</text><text x=\"240\" y=\"114\" font-size=\"16\" text-anchor=\"middle\">&#8728;</text><text x=\"160\" y=\"128\" font-size=\"26\" text-anchor=\"middle\">&#8746;</text"
        ],
        [
                "12_grumpy_professor",
                "122\" y=\"60\" font-size=\"30\" text-anchor=\"middle\">&#8726;</text><text x=\"192\" y=\"60\" font-size=\"30\" text-anchor=\"middle\">&#8725;</text><text x=\"124\" y=\"92\" font-size=\"30\" text-anchor=\"middle\">&#920;</text><text x=\"190\" y=\"92\" font-size=\"30\" text-anchor=\"middle\">&#920;</text><text x=\"160\" y=\"118\" font-size=\"26\" text-anchor=\"middle\" font-style=\"italic\">&#951;</text><text x=\"160\" y=\"150\" font-size=\"32\" text-anchor=\"middle\">&#8994;</text><text x=\"160\" y=\"176\" font-size=\"24\" text-anchor=\"middle\">&#8744;&#8744;&#8744;&#8744;&#8744;</text"
        ],
        [
                "13_devil",
                "110\" y=\"36\" font-size=\"36\" text-anchor=\"middle\" font-style=\"italic\">&#955;</text><text x=\"210\" y=\"36\" font-size=\"36\" text-anchor=\"middle\" font-style=\"italic\" transform=\"scale(-1,1) translate(-420,0)\">&#955;</text><text x=\"128\" y=\"84\" font-size=\"28\" text-anchor=\"middle\">&#8827;</text><text x=\"192\" y=\"84\" font-size=\"28\" text-anchor=\"middle\">&#8826;</text><text x=\"160\" y=\"126\" font-size=\"32\" text-anchor=\"middle\">&#8994;</text><text x=\"160\" y=\"158\" font-size=\"24\" text-anchor=\"middle\">&#8711;</text"
        ],
        [
                "14_king",
                "160\" y=\"36\" font-size=\"40\" text-anchor=\"middle\">&#8720;</text><text x=\"118\" y=\"90\" font-size=\"30\" text-anchor=\"middle\">&#8476;</text><text x=\"196\" y=\"90\" font-size=\"30\" text-anchor=\"middle\">&#8465;</text><text x=\"162\" y=\"116\" font-size=\"24\" text-anchor=\"middle\" font-style=\"italic\">&#567;</text><text x=\"160\" y=\"136\" font-size=\"28\" text-anchor=\"middle\">&#8764;</text><text x=\"160\" y=\"164\" font-size=\"38\" text-anchor=\"middle\">&#8776;</text"
        ],
        [
                "15_punk",
                "160\" y=\"42\" font-size=\"44\" text-anchor=\"middle\" transform=\"rotate(-15 160 30)\">&#8501;</text><text x=\"126\" y=\"94\" font-size=\"28\" text-anchor=\"middle\">&#8709;</text><text x=\"194\" y=\"94\" font-size=\"28\" text-anchor=\"middle\">&#8709;</text><text x=\"160\" y=\"136\" font-size=\"30\" text-anchor=\"middle\">&#8846;</text"
        ],
        [
                "16_gentleman",
                "160\" y=\"38\" font-size=\"42\" text-anchor=\"middle\">&#928;</text><text x=\"124\" y=\"94\" font-size=\"36\" text-anchor=\"middle\">&#8857;</text><text x=\"196\" y=\"94\" font-size=\"24\" text-anchor=\"middle\">&#8226;</text><text x=\"116\" y=\"122\" font-size=\"24\" text-anchor=\"middle\">&#8768;</text><text x=\"168\" y=\"124\" font-size=\"30\" text-anchor=\"middle\">&#8764;&#8764;</text><text x=\"160\" y=\"162\" font-size=\"34\" text-anchor=\"middle\">&#8904;</text"
        ],
        [
                "17_owl",
                "118\" y=\"22\" font-size=\"26\" text-anchor=\"middle\">&#8242;</text><text x=\"200\" y=\"22\" font-size=\"26\" text-anchor=\"middle\" transform=\"scale(-1,1) translate(-400,0)\">&#8242;</text><text x=\"124\" y=\"80\" font-size=\"40\" text-anchor=\"middle\">&#934;</text><text x=\"196\" y=\"80\" font-size=\"40\" text-anchor=\"middle\">&#934;</text><text x=\"72\" y=\"86\" font-size=\"54\" text-anchor=\"middle\">{</text><text x=\"248\" y=\"86\" font-size=\"54\" text-anchor=\"middle\">}</text><text x=\"160\" y=\"112\" font-size=\"22\" text-anchor=\"middle\">&#8711;</text><text x=\"160\" y=\"160\" font-size=\"24\" text-anchor=\"middle\">&#8869; &#8869;</text"
        ],
        [
                "18_alien",
                "160\" y=\"30\" font-size=\"30\" text-anchor=\"middle\" font-style=\"italic\">&#968;</text><text x=\"126\" y=\"90\" font-size=\"38\" text-anchor=\"middle\" transform=\"rotate(25 126 80)\">&#8709;</text><text x=\"194\" y=\"90\" font-size=\"38\" text-anchor=\"middle\" transform=\"rotate(-25 194 80)\">&#8709;</text><text x=\"160\" y=\"134\" font-size=\"26\" text-anchor=\"middle\">&#183;</text"
        ],
        [
                "19_frog",
                "126\" y=\"36\" font-size=\"34\" text-anchor=\"middle\">&#8857;</text><text x=\"194\" y=\"36\" font-size=\"34\" text-anchor=\"middle\">&#8857;</text><text x=\"152\" y=\"76\" font-size=\"18\" text-anchor=\"middle\">&#183;</text><text x=\"168\" y=\"76\" font-size=\"18\" text-anchor=\"middle\">&#183;</text><text x=\"160\" y=\"118\" font-size=\"72\" text-anchor=\"middle\">&#8995;</text"
        ],
        [
                "20_clown",
                "86\" y=\"62\" font-size=\"36\" text-anchor=\"middle\" transform=\"scale(-1,1) translate(-172,0)\">&#167;</text><text x=\"234\" y=\"62\" font-size=\"36\" text-anchor=\"middle\">&#167;</text><text x=\"130\" y=\"86\" font-size=\"28\" text-anchor=\"middle\">&#8727;</text><text x=\"190\" y=\"86\" font-size=\"28\" text-anchor=\"middle\">&#8727;</text><text x=\"160\" y=\"114\" font-size=\"30\" text-anchor=\"middle\">&#8859;</text><text x=\"160\" y=\"148\" font-size=\"40\" text-anchor=\"middle\">&#8746;</text"
        ],
        [
                "21_ghost",
                "160\" y=\"122\" font-size=\"110\" text-anchor=\"middle\">&#937;</text><text x=\"146\" y=\"92\" font-size=\"20\" text-anchor=\"middle\">&#8226;</text><text x=\"178\" y=\"92\" font-size=\"20\" text-anchor=\"middle\">&#8226;</text><text x=\"162\" y=\"114\" font-size=\"18\" text-anchor=\"middle\">&#8728;</text"
        ],
        [
                "22_rabbit",
                "132\" y=\"34\" font-size=\"40\" text-anchor=\"middle\" transform=\"scale(1,1.8)\">&#8745;</text><text x=\"188\" y=\"34\" font-size=\"40\" text-anchor=\"middle\" transform=\"scale(1,1.8)\">&#8745;</text><text x=\"138\" y=\"98\" font-size=\"26\" text-anchor=\"middle\">&#183;</text><text x=\"186\" y=\"98\" font-size=\"26\" text-anchor=\"middle\">&#183;</text><text x=\"160\" y=\"114\" font-size=\"18\" text-anchor=\"middle\">&#215;</text><text x=\"78\" y=\"106\" font-size=\"24\" text-anchor=\"middle\">&#8801;</text><text x=\"242\" y=\"106\" font-size=\"24\" text-anchor=\"middle\">&#8801;</text><text x=\"160\" y=\"134\" font-size=\"18\" text-anchor=\"middle\">&#8852;&#8852;</text"
        ]
    ];

    var img = document.getElementById("goblin-img");
    if (!img) return;

    var i;
    try {
        i = (parseInt(localStorage.getItem("goblin"), 10) + 1) % faces.length;
        if (isNaN(i)) i = 0;
        localStorage.setItem("goblin", i);
    } catch (e) {
        // No localStorage (private mode). Use a random face.
        i = Math.floor(Math.random() * faces.length);
    }

    img.src = "data:image/svg+xml," + encodeURIComponent(HEAD + faces[i][1] + TAIL);
    img.alt = "Maths goblin: " + faces[i][0].slice(3).replace(/_/g, " ");
})();
