"""Build frontend/goblin.js from the SVG faces in frontend/images/goblins/.

The faces go into the script as data URIs, thus the browser does not make a
second request when the script selects one. All the faces share the same SVG
header and footer, thus the script keeps those one time only and joins them
again at run time.

Run from the repo root after you add or remove a face:

    uv run python src/build_goblins.py
"""

import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FACES = ROOT / "frontend" / "images" / "goblins"
OUT = ROOT / "frontend" / "goblin.js"

TEMPLATE = """/* Maths goblins - https://github.com/jonathankeogh/maths-goblins
   Shows one face in the logo slot and steps to the next one on each page load.

   The faces are data URIs and this file is parsed immediately after the <img>,
   thus the first paint already shows the correct face: no second request, no
   swap, no movement. Generated by src/build_goblins.py - do not edit by hand.
*/
(function () {
    var HEAD = %(head)s;
    var TAIL = %(tail)s;
    var faces = %(faces)s;

    var img = document.getElementById("goblin-img");
    if (!img) return;

    var i;
    try {
        i = (parseInt(localStorage.getItem("goblin"), 10) + 1) %% faces.length;
        if (isNaN(i)) i = 0;
        localStorage.setItem("goblin", i);
    } catch (e) {
        // No localStorage (private mode). Use a random face.
        i = Math.floor(Math.random() * faces.length);
    }

    img.src = "data:image/svg+xml," + encodeURIComponent(HEAD + faces[i][1] + TAIL);
    img.alt = "Maths goblin: " + faces[i][0].slice(3).replace(/_/g, " ");
})();
"""


def common_prefix(items: list[str]) -> str:
    out = os.path.commonprefix(items)
    return out


def common_suffix(items: list[str]) -> str:
    flipped = [s[::-1] for s in items]
    return os.path.commonprefix(flipped)[::-1]


def main() -> None:
    paths = sorted(FACES.glob("*.svg"))
    if not paths:
        raise SystemExit(f"no SVG faces in {FACES}")

    names = [p.stem for p in paths]
    bodies = [p.read_text().strip() for p in paths]

    head = common_prefix(bodies)
    tail = common_suffix(bodies)
    middles = [b[len(head):len(b) - len(tail)] for b in bodies]

    js = TEMPLATE % {
        "head": json.dumps(head),
        "tail": json.dumps(tail),
        "faces": json.dumps(
            [[n, m] for n, m in zip(names, middles)], indent=8
        ).replace("\n]", "\n    ]"),
    }
    OUT.write_text(js)
    print(f"{len(paths)} faces -> {OUT.relative_to(ROOT)} ({len(js) / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
